name: "Setup Spack"
description: "Setup Spack and its dependencies"
inputs:
  os:
    description: "Operating system (ubuntu-18.04, ubuntu-20.04, macos-10.15)"
    required: true
  ref:
    description: "Version of Spack (develop, v0.16.2)"
    required: false
    default: develop
  concretizer:
    description: "Version of Spack (clingo, original)"
    required: false
    default: clingo
runs:
  using: "composite"
  steps:
    - name: Install Spack's dependencies
      run: |
        curl -LfSs -o spack.tar.zstd https://github.com/haampie-spack/setup-spack/releases/download/develop/${{ inputs.os }}.tar.zst
        TAR=tar
        if [ "$RUNNER_OS" == macOS ]; then TAR=gtar; fi
        $TAR --use-compress-program=zstd -xf spack.tar.zstd -C ~/
        echo "$HOME/.setup-spack/view/bin" >> $GITHUB_PATH
      shell: bash
    - name: Install Spack itself
      run: |
        git clone https://github.com/spack/spack.git
        (cd spack && git checkout "${{ inputs.ref }}")
        echo "$PWD/spack/bin" >> $GITHUB_PATH
        mkdir ~/.spack
        echo "config:"                                   > ~/.spack/config.yaml
        echo "  concretizer: ${{ inputs.concretizer }}" >> ~/.spack/config.yaml
      shell: bash
    - name: Show version
      run: spack --version
      shell: bash
