name: 'Setup Spack'
description: 'Setup Spack and its dependencies'
inputs:
  os:
    description: 'Runner operating system (ubuntu-18.04, ubuntu20.04)'
    required: true
runs:
  using: "composite"
  steps:
    - name: Install Spack's dependencies
      run: |
        curl -LfSs -o spack.tar.zstd https://github.com/haampie-spack/setup-spack/releases/download/develop/${{ inputs.os }}.tar.zst
        tar --use-compress-program="zstd" -xf spack.tar.zstd -C ~/
        echo "$HOME/.setup-spack/view/bin" >> $GITHUB_PATH
      shell: bash
    - name: Install Spack itself
      run: |
        git clone --depth 5 https://github.com/spack/spack.git
        echo "$PWD/spack/bin" >> $GITHUB_PATH
        mkdir ~/.spack
        echo "config:"                > ~/.spack/config.yaml
        echo "  concretizer: clingo" >> ~/.spack/config.yaml
      shell: bash
