name: Example

on:
  push:
    branches: ['main', 'release/*']
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-18.04
        - ubuntu-20.04
        - macos-10.15
    
    steps:
      - uses: actions/checkout@v1.0.0

      - name: Set up Spack
        uses: ./
        with:
          os: ${{ matrix.os }}
          ref: develop
      - run: spack --version
      - run: spack config blame config
      - run: spack install zlib
      - run: which patchelf
