name: Stable

on:
  push:
    branches: ['main', 'release/*']
  pull_request:

jobs:
  latest-stable:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-18.04
        - ubuntu-20.04
        - macos-10.15

    steps:
      - uses: actions/checkout@v1.0.0

      - name: Set up Spack
        uses: haampie-spack/setup-spack@v1.2.0
        with:
          os: ${{ matrix.os }}
          ref: develop
          concretizer: clingo

      - name: Concretize environment
        run: |
          spack --color always -e ./example-environment concretize -f

      - name: Restore Spack cache
        uses: actions/cache@v2
        with:
          path: ~/.spack-ci
          key: ${{ matrix.os }}-spack-${{ hashFiles('**/spack.lock') }}
          restore-keys: |
            ${{ matrix.os }}-spack

      - name: Install environment
        run: |
          spack --color always -e ./example-environment install -j3 -v